name: Daily Scraper

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        run: python app_auto.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: autos
          path: "*.xlsx"
          if-no-files-found: ignore

      - name: Commit seen links
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add seen_links/*.json

          if git diff --cached --quiet; then
            echo "Nincs változás."
          else
            git commit -m "Update seen links"
            git pull --rebase origin main
            git push origin HEAD:${{ github.ref_name }}
          fi